export const PERMISSION_RESOURCES = [
  'auth',
  'content',
  'content-types',
  'media',
  'seo',
  'menus',
  'forms',
  'search',
  'trash',
  'users',
  'roles',
  'tokens',
  'agent-tokens',
  'webhooks',
  'plugins',
  'locales',
  'settings',
  'audit',
  'dashboard',
  'mcp',
] as const;

export const PERMISSION_ACTIONS = [
  'read',
  'create',
  'update',
  'delete',
  'publish',
  'unpublish',
  'archive',
  'restore',
  'schedule',
  'revert',
  'locale',
  'duplicate',
  'enable',
  'disable',
  'register',
  'test',
  'validate',
  'import',
  'export',
  'revoke',
  'permanent-delete',
] as const;

export type PermissionResource = (typeof PERMISSION_RESOURCES)[number];
export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];
